import javax.swing.*;
import java.awt.*;
public class AmericanFlag{
	public static void main(String[] args){
		JFrame theGUI = new JFrame();
		theGUI.setTitle("American Flag");
		theGUI.setSize(300, 200);
		theGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		JPanel panel1 = new JPanel();
		panel1.setBackground(Color.blue);
		JPanel panel2 = new JPanel();
		panel2.setBackground(Color.red);
		JPanel panel3 = new JPanel();
		panel3.setBackground(Color.blue);
		JPanel panel4 = new JPanel();
		panel4.setBackground(Color.white);
		JPanel panel5 = new JPanel();
		panel5.setBackground(Color.blue);
		JPanel panel6 = new JPanel();
		panel6.setBackground(Color.red);
		JPanel panel7 = new JPanel();
		panel7.setBackground(Color.blue);
		JPanel panel8 = new JPanel();
		panel8.setBackground(Color.white);
		JPanel panel9 = new JPanel();
		panel9.setBackground(Color.blue);
		JPanel panel10 = new JPanel();
		panel10.setBackground(Color.red);
		JPanel panel11 = new JPanel();
		panel11.setBackground(Color.blue);
		JPanel panel12 = new JPanel();
		panel12.setBackground(Color.white);
		JPanel panel13 = new JPanel();
		panel13.setBackground(Color.blue);
		JPanel panel14 = new JPanel();
		panel14.setBackground(Color.red);
		JPanel panel15 = new JPanel();
		panel15.setBackground(Color.white);
		JPanel panel16 = new JPanel();
		panel16.setBackground(Color.white);
		JPanel panel17 = new JPanel();
		panel17.setBackground(Color.red);
		JPanel panel18 = new JPanel();
		panel18.setBackground(Color.red);
		JPanel panel19 = new JPanel();
		panel19.setBackground(Color.white);
		JPanel panel20 = new JPanel();
		panel20.setBackground(Color.white);
		JPanel panel21 = new JPanel();
		panel21.setBackground(Color.red);
		JPanel panel22 = new JPanel();
		panel22.setBackground(Color.red);
		JPanel panel23 = new JPanel();
		panel23.setBackground(Color.white);
		JPanel panel24 = new JPanel();
		panel24.setBackground(Color.white);
		JPanel panel25 = new JPanel();
		panel25.setBackground(Color.red);
		JPanel panel26 = new JPanel();
		panel26.setBackground(Color.red);
		Container pane = theGUI.getContentPane();
		pane.setLayout(new GridLayout(13, 2));
		pane.add(panel1);
		pane.add(panel2);
		pane.add(panel3);
		pane.add(panel4);
		pane.add(panel5);
		pane.add(panel6);
		pane.add(panel7);
		pane.add(panel8);
		pane.add(panel9);
		pane.add(panel10);
		pane.add(panel11);
		pane.add(panel12);
		pane.add(panel13);
		pane.add(panel14);
		pane.add(panel15);
		pane.add(panel16);
		pane.add(panel17);
		pane.add(panel18);
		pane.add(panel19);
		pane.add(panel20);
		pane.add(panel21);
		pane.add(panel22);
		pane.add(panel23);
		pane.add(panel24);
		pane.add(panel25);
		pane.add(panel26);
		theGUI.setVisible(true);
	}
}