import javax.swing.*;
import java.awt.*;
public class GreeceFlag{
	public static void main(String[] args){
		JFrame theGUI = new JFrame();
		theGUI.setTitle("Greek Flag");
		theGUI.setSize(300, 200);
		theGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		Color greek = new Color(58, 117, 196);
		JPanel panel1 = new JPanel();
		panel1.setBackground(Color.greek);
		JPanel panel2 = new JPanel();
		panel2.setBackground(Color.blue);
		JPanel panel3 = new JPanel();
		panel3.setBackground(Color.white);
		JPanel panel4 = new JPanel();
		panel4.setBackground(Color.blue);
		JPanel panel5 = new JPanel();
		panel5.setBackground(Color.blue);
		JPanel panel6 = new JPanel();
		panel6.setBackground(Color.blue);
		JPanel panel7 = new JPanel();
		panel7.setBackground(Color.blue);
		JPanel panel8 = new JPanel();
		panel8.setBackground(Color.blue);
		JPanel panel9 = new JPanel();
		panel9.setBackground(Color.blue);
		JPanel panel10 = new JPanel();
		panel10.setBackground(Color.blue);
		JPanel panel11 = new JPanel();
		panel11.setBackground(Color.blue);
		JPanel panel12 = new JPanel();
		panel12.setBackground(Color.blue);
		JPanel panel13 = new JPanel();
		panel13.setBackground(Color.blue);
		JPanel panel14 = new JPanel();
		panel14.setBackground(Color.blue);
		JPanel panel15 = new JPanel();
		panel15.setBackground(Color.blue);
		JPanel panel16 = new JPanel();
		panel16.setBackground(Color.blue);
		JPanel panel17 = new JPanel();
		panel17.setBackground(Color.blue);
		JPanel panel18 = new JPanel();
		panel18.setBackground(Color.white);
		JPanel panel19 = new JPanel();
		panel19.setBackground(Color.blue);
		JPanel panel20 = new JPanel();
		panel20.setBackground(Color.blue);
		JPanel panel21 = new JPanel();
		panel21.setBackground(Color.white);
		JPanel panel22 = new JPanel();
		panel22.setBackground(Color.white);
		JPanel panel23 = new JPanel();
		panel23.setBackground(Color.white);
		JPanel panel24 = new JPanel();
		panel24.setBackground(Color.white);
		JPanel panel25 = new JPanel();
		panel25.setBackground(Color.white);
		JPanel panel26 = new JPanel();
		panel26.setBackground(Color.white);
		JPanel panel27 = new JPanel();
		panel27.setBackground(Color.white);
		JPanel panel28 = new JPanel();
		panel28.setBackground(Color.white);
		JPanel panel29 = new JPanel();
		panel29.setBackground(Color.white);
		JPanel panel30 = new JPanel();
		panel30.setBackground(Color.white);
		JPanel panel31 = new JPanel();
		panel31.setBackground(Color.white);
		JPanel panel32 = new JPanel();
		panel32.setBackground(Color.white);
		JPanel panel33 = new JPanel();
		panel33.setBackground(Color.white);
		JPanel panel34 = new JPanel();
		panel34.setBackground(Color.white);
		JPanel panel35 = new JPanel();
		panel35.setBackground(Color.white);
		JPanel panel36 = new JPanel();
		panel36.setBackground(Color.blue);
		JPanel panel37 = new JPanel();
		panel37.setBackground(Color.blue);
		JPanel panel38 = new JPanel();
		panel38.setBackground(Color.blue);
		JPanel panel39 = new JPanel();
		panel39.setBackground(Color.blue);
		JPanel panel40 = new JPanel();
		panel40.setBackground(Color.blue);
		JPanel panel41 = new JPanel();
		panel41.setBackground(Color.blue);
		JPanel panel42 = new JPanel();
		panel42.setBackground(Color.blue);
		JPanel panel43 = new JPanel();
		panel43.setBackground(Color.blue);
		JPanel panel44 = new JPanel();
		panel44.setBackground(Color.blue);
		JPanel panel45 = new JPanel();
		panel45.setBackground(Color.blue);
		JPanel panel46 = new JPanel();
		panel46.setBackground(Color.blue);
		JPanel panel47 = new JPanel();
		panel47.setBackground(Color.blue);
		JPanel panel48 = new JPanel();
		panel48.setBackground(Color.white);
		JPanel panel49 = new JPanel();
		panel49.setBackground(Color.blue);
		JPanel panel50 = new JPanel();
		panel50.setBackground(Color.blue);
		JPanel panel51 = new JPanel();
		panel51.setBackground(Color.white);
		JPanel panel52 = new JPanel();
		panel52.setBackground(Color.white);
		JPanel panel53 = new JPanel();
		panel53.setBackground(Color.white);
		JPanel panel54 = new JPanel();
		panel54.setBackground(Color.white);
		JPanel panel55 = new JPanel();
		panel55.setBackground(Color.white);
		JPanel panel56 = new JPanel();
		panel56.setBackground(Color.white);
		JPanel panel57 = new JPanel();
		panel57.setBackground(Color.white);
		JPanel panel58 = new JPanel();
		panel58.setBackground(Color.white);
		JPanel panel59 = new JPanel();
		panel59.setBackground(Color.white);
		JPanel panel60 = new JPanel();
		panel60.setBackground(Color.white);
		JPanel panel61 = new JPanel();
		panel61.setBackground(Color.blue);
		JPanel panel62 = new JPanel();
		panel62.setBackground(Color.blue);
		JPanel panel63 = new JPanel();
		panel63.setBackground(Color.white);
		JPanel panel64 = new JPanel();
		panel64.setBackground(Color.blue);
		JPanel panel65 = new JPanel();
		panel65.setBackground(Color.blue);
		JPanel panel66 = new JPanel();
		panel66.setBackground(Color.blue);
		JPanel panel67 = new JPanel();
		panel67.setBackground(Color.blue);
		JPanel panel68 = new JPanel();
		panel68.setBackground(Color.blue);
		JPanel panel69 = new JPanel();
		panel69.setBackground(Color.blue);
		JPanel panel70 = new JPanel();
		panel70.setBackground(Color.blue);
		JPanel panel71 = new JPanel();
		panel71.setBackground(Color.blue);
		JPanel panel72 = new JPanel();
		panel72.setBackground(Color.blue);
		JPanel panel73 = new JPanel();
		panel73.setBackground(Color.blue);
		JPanel panel74 = new JPanel();
		panel74.setBackground(Color.blue);
		JPanel panel75 = new JPanel();
		panel75.setBackground(Color.blue);
		JPanel panel76 = new JPanel();
		panel76.setBackground(Color.white);
		JPanel panel77 = new JPanel();
		panel77.setBackground(Color.white);
		JPanel panel78 = new JPanel();
		panel78.setBackground(Color.white);
		JPanel panel79 = new JPanel();
		panel79.setBackground(Color.white);
		JPanel panel80 = new JPanel();
		panel80.setBackground(Color.white);
		JPanel panel81 = new JPanel();
		panel81.setBackground(Color.white);
		JPanel panel82 = new JPanel();
		panel82.setBackground(Color.white);
		JPanel panel83 = new JPanel();
		panel83.setBackground(Color.white);
		JPanel panel84 = new JPanel();
		panel84.setBackground(Color.white);
		JPanel panel85 = new JPanel();
		panel85.setBackground(Color.white);
		JPanel panel86 = new JPanel();
		panel86.setBackground(Color.white);
		JPanel panel87 = new JPanel();
		panel87.setBackground(Color.white);
		JPanel panel88 = new JPanel();
		panel88.setBackground(Color.white);
		JPanel panel89 = new JPanel();
		panel89.setBackground(Color.white);
		JPanel panel90 = new JPanel();
		panel90.setBackground(Color.white);
		JPanel panel91 = new JPanel();
		panel91.setBackground(Color.blue);
		JPanel panel92 = new JPanel();
		panel92.setBackground(Color.blue);
		JPanel panel93 = new JPanel();
		panel93.setBackground(Color.blue);
		JPanel panel94 = new JPanel();
		panel94.setBackground(Color.blue);
		JPanel panel95 = new JPanel();
		panel95.setBackground(Color.blue);
		JPanel panel96 = new JPanel();
		panel96.setBackground(Color.blue);
		JPanel panel97 = new JPanel();
		panel97.setBackground(Color.blue);
		JPanel panel98 = new JPanel();
		panel98.setBackground(Color.blue);
		JPanel panel99 = new JPanel();
		panel99.setBackground(Color.blue);
		JPanel panel100 = new JPanel();
		panel100.setBackground(Color.blue);
		JPanel panel101 = new JPanel();
		panel101.setBackground(Color.blue);
		JPanel panel102 = new JPanel();
		panel102.setBackground(Color.blue);
		JPanel panel103 = new JPanel();
		panel103.setBackground(Color.blue);
		JPanel panel104 = new JPanel();
		panel104.setBackground(Color.blue);
		JPanel panel105 = new JPanel();
		panel105.setBackground(Color.blue);
		JPanel panel106 = new JPanel();
		panel106.setBackground(Color.white);
		JPanel panel107 = new JPanel();
		panel107.setBackground(Color.white);
		JPanel panel108 = new JPanel();
		panel108.setBackground(Color.white);
		JPanel panel109 = new JPanel();
		panel109.setBackground(Color.white);
		JPanel panel110 = new JPanel();
		panel110.setBackground(Color.white);
		JPanel panel111 = new JPanel();
		panel111.setBackground(Color.white);
		JPanel panel112 = new JPanel();
		panel112.setBackground(Color.white);
		JPanel panel113 = new JPanel();
		panel113.setBackground(Color.white);
		JPanel panel114 = new JPanel();
		panel114.setBackground(Color.white);
		JPanel panel115 = new JPanel();
		panel115.setBackground(Color.white);
		JPanel panel116 = new JPanel();
		panel116.setBackground(Color.white);
		JPanel panel117 = new JPanel();
		panel117.setBackground(Color.white);
		JPanel panel118 = new JPanel();
		panel118.setBackground(Color.white);
		JPanel panel119 = new JPanel();
		panel119.setBackground(Color.white);
		JPanel panel120 = new JPanel();
		panel120.setBackground(Color.white);
		JPanel panel121 = new JPanel();
		panel121.setBackground(Color.blue);
		JPanel panel122 = new JPanel();
		panel122.setBackground(Color.blue);
		JPanel panel123 = new JPanel();
		panel123.setBackground(Color.blue);
		JPanel panel124 = new JPanel();
		panel124.setBackground(Color.blue);
		JPanel panel125 = new JPanel();
		panel125.setBackground(Color.blue);
		JPanel panel126 = new JPanel();
		panel126.setBackground(Color.blue);
		JPanel panel127 = new JPanel();
		panel127.setBackground(Color.blue);
		JPanel panel128 = new JPanel();
		panel128.setBackground(Color.blue);
		JPanel panel129 = new JPanel();
		panel129.setBackground(Color.blue);
		JPanel panel130 = new JPanel();
		panel130.setBackground(Color.blue);
		JPanel panel131 = new JPanel();
		panel131.setBackground(Color.blue);
		JPanel panel132 = new JPanel();
		panel132.setBackground(Color.blue);
		JPanel panel133 = new JPanel();
		panel133.setBackground(Color.blue);
		JPanel panel134 = new JPanel();
		panel134.setBackground(Color.blue);
		JPanel panel135 = new JPanel();
		panel135.setBackground(Color.blue);
		Container pane = theGUI.getContentPane();
		pane.setLayout(new GridLayout(9, 15));
		pane.add(panel1);
		pane.add(panel2);
		pane.add(panel3);
		pane.add(panel4);
		pane.add(panel5);
		pane.add(panel6);
		pane.add(panel7);
		pane.add(panel8);
		pane.add(panel9);
		pane.add(panel10);
		pane.add(panel11);
		pane.add(panel12);
		pane.add(panel13);
		pane.add(panel14);
		pane.add(panel15);
		pane.add(panel16);
		pane.add(panel17);
		pane.add(panel18);
		pane.add(panel19);
		pane.add(panel20);
		pane.add(panel21);
		pane.add(panel22);
		pane.add(panel23);
		pane.add(panel24);
		pane.add(panel25);
		pane.add(panel26);
		pane.add(panel27);
		pane.add(panel28);
		pane.add(panel29);
		pane.add(panel30);
		pane.add(panel31);
		pane.add(panel32);
		pane.add(panel33);
		pane.add(panel34);
		pane.add(panel35);
		pane.add(panel36);
		pane.add(panel37);
		pane.add(panel38);
		pane.add(panel39);
		pane.add(panel40);
		pane.add(panel41);
		pane.add(panel42);
		pane.add(panel43);
		pane.add(panel44);
		pane.add(panel45);
		pane.add(panel46);
		pane.add(panel47);
		pane.add(panel48);
		pane.add(panel49);
		pane.add(panel50);
		pane.add(panel51);
		pane.add(panel52);
		pane.add(panel53);
		pane.add(panel54);
		pane.add(panel55);
		pane.add(panel56);
		pane.add(panel57);
		pane.add(panel58);
		pane.add(panel59);
		pane.add(panel60);
		pane.add(panel61);
		pane.add(panel62);
		pane.add(panel63);
		pane.add(panel64);
		pane.add(panel65);
		pane.add(panel66);
		pane.add(panel67);
		pane.add(panel68);
		pane.add(panel69);
		pane.add(panel70);
		pane.add(panel71);
		pane.add(panel72);
		pane.add(panel73);
		pane.add(panel74);
		pane.add(panel75);
		pane.add(panel76);
		pane.add(panel77);
		pane.add(panel78);
		pane.add(panel79);
		pane.add(panel80);
		pane.add(panel81);
		pane.add(panel82);
		pane.add(panel83);
		pane.add(panel84);
		pane.add(panel85);
		pane.add(panel86);
		pane.add(panel87);
		pane.add(panel88);
		pane.add(panel89);
		pane.add(panel90);
		pane.add(panel91);
		pane.add(panel92);
		pane.add(panel93);
		pane.add(panel94);
		pane.add(panel95);
		pane.add(panel96);
		pane.add(panel97);
		pane.add(panel98);
		pane.add(panel99);
		pane.add(panel100);
		pane.add(panel101);
		pane.add(panel102);
		pane.add(panel103);
		pane.add(panel104);
		pane.add(panel105);
		pane.add(panel106);
		pane.add(panel107);
		pane.add(panel108);
		pane.add(panel109);
		pane.add(panel110);
		pane.add(panel111);
		pane.add(panel112);
		pane.add(panel113);
		pane.add(panel114);
		pane.add(panel115);
		pane.add(panel116);
		pane.add(panel117);
		pane.add(panel118);
		pane.add(panel119);
		pane.add(panel120);
		pane.add(panel121);
		pane.add(panel122);
		pane.add(panel123);
		pane.add(panel124);
		pane.add(panel125);
		pane.add(panel126);
		pane.add(panel127);
		pane.add(panel128);
		pane.add(panel129);
		pane.add(panel130);
		pane.add(panel131);
		pane.add(panel132);
		pane.add(panel133);
		pane.add(panel134);
		pane.add(panel135);
		theGUI.setVisible(true);
	}
}